[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "colorama",
    "appdirs",
    "requests>=2.28.2,<3.0",
    "pyyaml>=6.0.1,<7.0",
    "Jinja2",
    "bitstring"
]
build-backend = "setuptools.build_meta"
